home/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from constance import config

from . import views

app_name = 'home'
urlpatterns = [
  # ex: /
  url(r'^$', views.get_index, name = 'index'),
  url(r'^photos/$', views.get_index_photos, name = 'index-photos'),
  url(r'^(?P<category>[\w-]+)/$', views.get_category, name = 'category'),
  url(r'^(?P<category>[\w-]+)/pages/$', views.get_category_pages, name = 'category-pages'),
  url(r'^(?P<category>[\w-]+)/(?P<page>[\w-]+)/$', views.get_category, name = 'page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
  url(r'^travel/', include('travel.urls')),
  url(r'^admin/', admin.site.urls),
  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
  url(r'^', include('home.urls')),
]

travel/urls.py
from django.conf.urls import url

from . import views

app_name = 'travel'
urlpatterns = [
  # ex: /travel/
  url(r'^$', views.index, name = 'index'),
  # ex: /travel/location/
  url(r'^location/$', views.location, name = 'location'),
  url(r'^places/$', views.places, name = 'places'),
  url(r'^world/$', views.world, name = 'world')
]

travel/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import get_thumbnail
from adminsortable.models import SortableMixin
from django.utils.encoding import python_2_unicode_compatible

from .includes.exif import Exif


class WorldPlace(models.Model):
  TYPE = (
    ('been', 'Been'),
    ('plan', 'Plan'),
    ('home', 'Home'),
  );
  name = models.CharField(max_length = 196)
  type = models.CharField(max_length = 4, choices = TYPE)
  latitude = models.DecimalField(max_digits = 17, decimal_places = 14)
  longitude = models.DecimalField(max_digits = 17, decimal_places = 14)
  

@python_2_unicode_compatible
class Place(SortableMixin):
  PLAN_TIME = (
    ('allday', 'All day'),
    ('midnight', 'Midnight'),
    ('dawn', 'Dawn'),
    ('morning', 'Morning'),
    ('noon', ' Noon'),
    ('afternoon', 'Afternoon'),
    ('dust', 'Dust'),
    ('evening', 'Evening'),
  );

  type = models.CharField(max_length = 196)
  name = models.CharField(max_length = 196)
  name_en = models.CharField(max_length = 196, null = True, blank = True)
  search = models.CharField(max_length = 196, null = True, blank = True)
  icon = models.URLField(null = True, blank = True)
  address = models.TextField()
  latitude = models.DecimalField(max_digits = 17, decimal_places = 14)
  longitude = models.DecimalField(max_digits = 17, decimal_places = 14)

  # travel_type = models.CharField(max_length = 7, choices = TRAVEL_TYPE, null = True, blank = True)
  # transit_no = models.CharField(max_length = 19, null = True, blank = True)
  # transit_time = models.TimeField(null = True, blank = True)
  # transit_arrive_time = models.TimeField(null = True, blank = True)
  # transit_ticket_price = models.DecimalField(max_digits = 9, decimal_places = 2, null = True, blank = True)

  plan_date = models.DateField(null = True, blank = True)
  plan_time = models.CharField(max_length = 9, choices = PLAN_TIME, null = True, blank = True)

  added_at = models.DateTimeField()
  sort = models.PositiveIntegerField(default = 0, editable = False, db_index = True)

  

  class Meta:
    ordering = ['sort']

  def __str__(self):
    return self.name + ' @ ' + str(self.plan_date) + ' ' + str(self.plan_time)
  

class TravelConstraint(models.Model):
  TYPE = (
    ('departure-before', 'Must departure before'),
    ('departure-after', 'Must departure after'),
    ('arrive-before', 'Must arrive before'),
    ('arrive-after', 'Must arrive after'),
  );

  type = models.CharField(max_length = 16, choices = TYPE)
  time = models.TimeField()
  place = models.ForeignKey(Place)


class Transit(models.Model):
  # TYPE = (
  #   ('driving', 'Driving'),
  #   ('walking', 'Walking'),
  #   ('train', 'Train'),
  #   ('public', 'Public transport'),
  #   ('flight', 'Flight'),
  #   ('ferry', 'Ferry'),
  # );

  STATUS = (
    ('decided', 'Decided'),
    ('yet-decided', 'Yet decided'),
  )

  # type = models.CharField(max_length = 7, choices = TYPE)
  status = models.CharField(max_length = 11, choices = STATUS)
  # no = models.CharField(max_length = 19, null = True, blank = True)
  # no_en = models.CharField(max_length = 19, null = True, blank = True)
  # departure_time = models.TimeField(null = True, blank = True)
  # arrive_time = models.TimeField(null = True, blank = True)
  ticket_price = models.DecimalField(max_digits = 9, decimal_places = 2, null = True, blank = True)
  a = models.OneToOneField(Place, related_name = 'from+')
  b = models.OneToOneField(Place, related_name = 'to+')


class Photo(models.Model):
  name = models.CharField(max_length = 196, null = True, blank = True)
  description = models.TextField(null = True, blank = True)
  user = models.ForeignKey(User)
  original_image = models.ImageField(upload_to = 'travel/photo')
  stylish_image = models.ImageField(upload_to = 'travel/photo', null = True, blank = True)
  added_at = models.DateTimeField()

  @property
  def image_thumbnail(self):
    return self.thumbnail_url()

  @property
  def image_size(self):
    if self.stylish_image:
      return self.stylish_image_size()
    else:
      return self.original_image_size()

  @property
  def original_image_url(self):
    return self.original_image.url

  @property
  def stylish_image_url(self):
    if self.stylish_image:
      return self.stylish_image.url


  def admin_thumbnail(self):
    thumbnail_url = self.thumbnail_url(125)
    return '<image src="{0}">'.format(thumbnail_url)

  admin_thumbnail.short_description = 'Thumb'
  admin_thumbnail.allow_tags = True


  def original_image_size(self):
    return self.original_image.width, self.original_image.height

  def stylish_image_size(self):
    if self.stylish_image:
      return self.stylish_image.width, self.stylish_image.height

  def thumbnail_url(self, maxSize = 800):
    if self.stylish_image:
      image = self.stylish_image
      size = self.stylish_image_size()
    elif self.original_image:
      image = self.original_image
      size = self.original_image_size()

    if (size[0] >= size[1]):
      size = '{0}x{1}'.format(maxSize, maxSize * size[1] / size[0])
    else:
      size = '{0}x{1}'.format(maxSize * size[0] / size[1], maxSize)

    thumbnail = get_thumbnail(image, size, quality=99)
    return thumbnail.url

  def image_exif(self):
    return Exif(self.original_image)
    

travel/views.py
import base64, json, boto3, time, os

from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth import authenticate
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt

from home.includes.serializer import ExtJsonSerializer
from .models import Place, WorldPlace

def index(request):
  return render(request, 'travel/index.html')

@csrf_exempt
def places(request):
  if request.method == 'GET':
    places = Place.objects.all()
    return HttpResponse(ExtJsonSerializer().serialize(places, 
      fields = ['name', 'icon', 'type', 'address', 
        'latitude', 'longitude', 'plan_date', 'plan_time']))

  elif request.method == 'POST':
    data = json.loads(request.body)
    place = Place(
      name = data['name'], 
      search = data['name'],
      icon = data['icon'],
      type = data['type'],
      address = data['address'],
      latitude = data['latitude'],
      longitude = data['longitude'],
      added_at = timezone.now(),
    )
    place.save()

    return None

@require_http_methods(['GET'])
def world(request):
  return render(request, 'travel/world.html', {
    'places': WorldPlace.objects.all()
  })

@require_http_methods(['POST'])
@csrf_exempt
def location(request):
  basic_auth = request.META['HTTP_AUTHORIZATION'].split()
  username, password = base64.b64decode(basic_auth[1]).split(':')
  user = authenticate(username = username, password = password)
  if user is not None and user.is_active:
    data = json.loads(request.body)
    if data['_type'] == 'location':
      if 'DYNAMODB_REGION' in os.environ:
        client = boto3.client('dynamodb', region_name = os.environ['DYNAMODB_REGION'])
      else:
        client = boto3.client('dynamodb');

      location = {
        'user_id': { 'N': str(user.id) },
        'battery': { 'N': str(data['batt']) },
        'latitude': { 'N': str(data['lat']) },
        'longitude': { 'N': str(data['lon']) },
        'network': { 'S': str(data['conn']) },
        'tracker_id': { 'S': str(data['tid']) },
        'visited_at': { 'N': str(data['tst']) },
      }
      if 'acc' in data:
        location['accuracy'] = { 'N': str(data['acc']) }
      if 'alt' in data:
        location['alt'] = { 'N': str(data['alt']) }
      if 'cog' in data:
        location['heading'] = { 'N': str(data['cog']) }
      if 'desc' in data:
        location['waypoint'] = { 'N': str(data['desc']) }
      if 'event' in data:
        location['event'] = { 'N': str(data['event']) }
      if 'rad' in data:
        location['radius'] = { 'N': str(data['rad']) }
      if 'vac' in data:
        location['altitude_accurancy'] = { 'N': str(data['vac']) }
      if 'vel' in data:
        location['velocity'] = { 'N': str(data['vel']) }
      if 'p' in data:
        location['barometric_pressure'] = { 'N': str(data['p']) }
      if 't' in data:
        location['trigger'] = { 'S': str(data['t']) }


      result = client.put_item(
        TableName = 'locations',
        Item = location
      )
      return HttpResponse(json.dumps({
        'result': result
      }), content_type = 'application/json')

  response = HttpResponse()
  response.status_code = 401
  return response

travel/templates/travel/index.html
{% load static from staticfiles %}

<link rel="stylesheet" href="{% static 'home/css/common.css' %}">
<link rel="stylesheet" href="{% static 'home/css/map.css' %}">

<div class="p-map">
  <div 
    data-component="travel-map" 
    data-prop-url-add-wanna-go="{% url 'travel:places' %}"
    data-prop-url-get-travel-places="{% url 'travel:places' %}"></div>
</div>

<script src="{% static 'home/js/app.js' %}"></script>

travel/templates/travel/world.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>芋头丢丢环游世界</title>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js"></script>
    <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css" rel="stylesheet" />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<div id='map'></div>
<script>
mapboxgl.accessToken = 'pk.eyJ1IjoieXR4aXV4aXUiLCJhIjoiY2l4NnByYTZkMDEyOTJ5bXN2OGNyMzU0YSJ9.2XjIDOvVVsT4-WWcdNuBIA';

var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/ytxiuxiu/ciys3jbq900042srzlwe64m4r', //stylesheet location
    center: [116.1165966, 39.938545], // starting position
    zoom: 2 // starting zoom
});

var places = [
{% for place in places %}
    {
        name: '{{ place.name }}',
        coordinates: [{{ place.latitude }}, {{ place.longitude }}],
        type: '{{ place.type }}'
    },
{% endfor %}
];

var been = {
    type: 'FeatureCollection',
    features: []
};
var plan = {
    type: 'FeatureCollection',
    features: []
};
var home = {
    type: 'FeatureCollection',
    features: []
};

var icons = {
    been: '{% static "travel/images/been.png" %}',
    home: '{% static "travel/images/home.png" %}',
    plan: '{% static "travel/images/plan.png" %}'
};

for (var i = 0; i < places.length; i++) {
    var place = places[i];
    var feature = {
        type: 'Feature',
        geometry: {
            type: 'Point',
            coordinates: [place.coordinates[1], place.coordinates[0]]
        },
        properties: {
            name: place.name,
            icon: place.type,
            color: place.type == 'been' ? 
                'rgba(0, 0, 0, 1)' : 
                'rgba(150, 150, 150, 1)'
        }
    };

    if (place.type == 'been') {
        been.features.push(feature);
    } else if (place.type == 'plan') {
        plan.features.push(feature);
    } else if (place.type == 'home') {
        home.features.push(feature);
    }
}

function addText(id, features, color) {
    map.addLayer({
        id: id,
        type: 'symbol',
        source: {
            type: 'geojson',
            data: features,
        },
        layout: {
            'text-field': '{name}',
            'text-size': 16,
            'text-offset': [0, 0.3],
            'text-anchor': 'top'
        },
        paint: {
            'text-color': color
        }
    });
}
function addIcon(features) {
    for (var i = 0; i < features.features.length; i++) {
        var marker = features.features[i];
        var el = document.createElement('div');
        el.className = 'marker';
        el.style.backgroundImage = 'url(' + icons[marker.properties.icon] + ')';
        el.style.width = '8px';
        el.style.height = '8px';

        el.addEventListener('click', function() {
            // window.alert(marker.properties.message);
        });

        // add marker to map
        new mapboxgl.Marker(el, {offset: [-4, -4]}) 
            .setLngLat(marker.geometry.coordinates)
            .addTo(map);
    }
}

map.on('load', function () {
    addText('been', been, 'rgba(0, 0, 0, 1)');
    addText('plan', plan, 'rgba(100, 100, 100, 1)');
    addText('home', home, 'rgba(0, 0, 0, 1)');

    addIcon(been);
    addIcon(plan);
    addIcon(home);
});
</script>

</body>
</html>