home/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from constance import config

from . import views

app_name = 'home'
urlpatterns = [
  # ex: /
  url(r'^$', views.get_index, name = 'index'),
  url(r'^photos/$', views.get_index_photos, name = 'index-photos'),
  url(r'^(?P<category>[\w-]+)/$', views.get_category, name = 'category'),
  url(r'^(?P<category>[\w-]+)/pages/$', views.get_category_pages, name = 'category-pages'),
  url(r'^(?P<category>[\w-]+)/(?P<page>[\w-]+)/$', views.get_category, name = 'page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
  url(r'^travel/', include('travel.urls')),
  url(r'^admin/', admin.site.urls),
  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
  url(r'^', include('home.urls')),
]

home/models.py
from __future__ import unicode_literals

from django.db import models
from sorl.thumbnail import get_thumbnail
from ckeditor_uploader.fields import RichTextUploadingField
from adminsortable.models import SortableMixin
from django.utils.encoding import python_2_unicode_compatible

from django.contrib.auth.models import User


@python_2_unicode_compatible
class GroundFloorTimber(models.Model):
  name = models.CharField(max_length = 192, null = True, blank = True)
  image = models.ImageField(upload_to = 'ground-floor-timber')
  added_at = models.DateTimeField()

  def image_thumbnail(self):
    if self.image:
      thumbnail = get_thumbnail(self.image, '125x125')
      return u'<image src="%s">' % thumbnail.url
    else:
      return u'-'
  image_thumbnail.short_description = 'Thumb'
  image_thumbnail.allow_tags = True

  def __str__(self):
    if self.name:
      return self.name
    else:
      return 'Image'

@python_2_unicode_compatible
class Category(models.Model):
  name = models.CharField(max_length = 192)
  link = models.CharField(max_length = 192)
  desc = RichTextUploadingField(null = True, blank = True)

  def __str__(self):
    return self.name

@python_2_unicode_compatible
class Page(models.Model):
  name = models.CharField(max_length = 192)
  link = models.CharField(max_length = 192)
  cover_image = models.ImageField(upload_to = 'page-cover', null = True, blank = True)
  user = models.ForeignKey(User)
  category = models.ForeignKey(Category, null = True, blank = True)
  created_at = models.DateTimeField()
  modified_at = models.DateTimeField()

  @property
  def image_thumbnail(self):
    return self.thumbnail_url()

  @property
  def image_size(self):
    if self.cover_image:
      return self.cover_image.width, self.cover_image.height

  def thumbnail_url(self, width = 800, height = 800):
    size = '{0}x{1}'.format(width, height)
    if self.cover_image:
      thumbnail = get_thumbnail(self.cover_image, size)
      return thumbnail.url

  def __str__(self):
    return self.name

class PageSection(models.Model):
  CONTENT_WIDTH = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
  )

  CONTENT_OFFSET = (
    ('0', '0'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
  )

  content = RichTextUploadingField()
  content_width = models.CharField(max_length = 2, choices = CONTENT_WIDTH, default = 12)
  content_offset = models.CharField(max_length = 2, choices = CONTENT_OFFSET, default = 0)
  page = models.ForeignKey(Page)

@python_2_unicode_compatible
class Link(SortableMixin):
  TARGET = (
    ('_blank', 'New window/tab'),
    ('_self', 'Current window'),
  )
  TYPE = (
    ('p', 'Page'),
    ('c', 'Category'),
    ('e', 'External'),
  )

  name = models.CharField(max_length = 192)
  link_text = models.CharField(max_length = 192)
  target = models.CharField(max_length = 7, choices = TARGET, default = '_self')
  type = models.CharField(max_length = 1, choices = TYPE, default = 'c')
  url = models.CharField(max_length = 255, null = True, blank = True)
  category = models.ForeignKey(Category, related_name = 'link_category', null = True, blank = True)
  page = models.ForeignKey(Page, related_name = 'link_category', null = True, blank = True)
  sort = models.PositiveIntegerField(default = 0, editable = False, db_index = True)

  class Meta:
    ordering = ['sort']

  def __str__(self):
    return self.name

home/views.py
import logging

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, JsonResponse

from .includes.serializer import ExtJsonSerializer
from .models import GroundFloorTimber, Category, Page, PageSection, Link
from travel.models import Photo


def get_index(request):
  return render(request, 'home/index.html', {
    'ground_floor_timber': GroundFloorTimber.objects.order_by('?').first(),
    'nav_links': Link.objects.all(),
  })

def get_index_photos(request):
  photos = Photo.objects.order_by('-added_at')[:10]
  return HttpResponse(ExtJsonSerializer().serialize(photos, 
    fields = ['name', 'image_thumbnail', 'image_size', 'original_image_url', 'stylish_image_url']))

def get_page(request, page):
  page = get_object_or_404(Page, link = page)
  page_sections = PageSection.objects.filter(page = page)
  return render(request, 'home/page.html', {
    'page': page,
    'page_sections': page_sections,
    'nav_links': Link.objects.all(),
  })

def get_category(request, category, page = None):
  # categories / top-level pages
  if page is None:
    try:
      category = Category.objects.get(link = category)
      return render(request, 'home/category.html', {
        'ground_floor_timber': GroundFloorTimber.objects.order_by('?').first(),
        'nav_links': Link.objects.all(),
        'category': category,
      })

    except (KeyError, Category.DoesNotExist):
      return get_page(request, category)

  # pages
  else:
    return get_page(request, page)
  
def get_category_pages(request, category):
  category = Category.objects.get(link = category)
  pages = Page.objects.filter(category = category)
  return HttpResponse(ExtJsonSerializer().serialize(pages, 
    fields = ['name', 'link', 'category.link', 'image_thumbnail', 'image_size']))

home/templates/home/category.html
{% extends './layouts/with-ground.html' %}

{% load static from staticfiles %}
{% load thumbnail %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'home/css/category.css' %}">
{% endblock %}

{% block grid %}p-category{% endblock %}

{% block floors %}
  <div data-component="floor-photo" data-prop-url="{% url 'home:category-pages' category.link %}"></div>
{% endblock %}

home/templates/home/index.html
{% extends './layouts/with-ground.html' %}

{% load static from staticfiles %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'home/css/index.css' %}">
{% endblock %}

{% block grid %}p-index{% endblock %}

{% block floors %}
  <div class="m-floor m-floor-photo col-md-12">:: Photographs</div>
  <div data-component="floor-photo" data-prop-url="{% url 'home:index-photos' %}" data-n-prop-height="200"></div>
{% endblock %}

home/templates/home/page.html
{% extends './layouts/base.html' %}

{% load static from staticfiles %}
{% load mathfilters %}

{% block grid %}p-page{% endblock %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'home/css/page.css' %}">
{% endblock %}

{% block building %}
  <div class="m-floor m-floor-page col-md-12">
    {% include './modules/nav-ground.html' %}
    {% include './modules/window.html' %}
    <div class="timber">
      {% for section in page_sections %}
        {% with width=section.content_width offset=section.content_offset %}
          <div class="content t-text col-md-{{ width }} col-md-offset-{{ offset }} col-sm-{{ width }} col-sm-offset-{{ offset }}">
            {{ section.content|safe }}
          </div>
        {% endwith %}
      {% endfor %}
    </div>
  </div>
{% endblock %}